apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "pyrsia-node.name" . }}
  annotations:
spec:
  replicas: {{ .Values.replicaCount }}
  updateStrategy:
    type: RollingUpdate
  serviceName: {{ include "pyrsia-node.name" . }}
  selector:
    matchLabels:
      app:  {{ include "pyrsia-node.name" . }}
      tier: frontend
      track: stable
  template:
    metadata:
      labels:
        app: pyrsia-node
        tier: frontend
        track: stable
    spec:
      containers:
        - name: {{ include "pyrsia-node.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}        
          ports:
            - name: pyrsia
              containerPort: {{.Values.pyrsia.ports.pyrsia}}
            - name: p2p
              containerPort: {{ .Values.pyrsia.ports.p2p}}
          env:
            - name: PYRSIA_ARTIFACT_PATH
              value: "/usr/local/var/pyrsia"
            - name: PYRSIA_KEYPAIR
              value: /usr/local/var/pyrsia-p2p-keys/ed25519.ser
          volumeMounts:
            # name must match the volume name below
            - name: pyrsia-storage
              mountPath: "/usr/local/var/pyrsia"
            - name: pyrsia-p2p-keys
              mountPath: /usr/local/var/pyrsia-p2p-keys
  volumeClaimTemplates:
    - metadata:
        name: pyrsia-storage
      spec:
        storageClassName: standard
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{.Values.pyrsia.storage.size}}
    - metadata:
        name: pyrsia-p2p-keys
      spec:
        storageClassName: csi-gce-pd
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10M      
